#! /bin/bash
cleanup() {
	find . -iname 'obj' -type d -exec rm -rv {} \;
	return 0
}
run_specs() {
	NUNIT_CONSOLE=./tools/nunit-console.exe ./tools/nunit-color-console.exe ./bin/Debug/$1/NUnit.Should.Specs.dll
}

rm -rfv bin                                            && \
cleanup                                                && \

xbuild NUnit.Should.NET20.sln                          && \
echo -e "\n[Running Specs against .NET 2.0]\n"         && \
run_specs NET20                                        && \

cleanup                                                && \
xbuild NUnit.Should.NET30.sln                          && \
echo -e "\n[Running Specs against .NET 3.0]\n"         && \
run_specs NET30
